# Generated by Django 4.2.7 on 2023-11-22 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('id_telegram', models.IntegerField(null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='telegram_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.telegramuser'),
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.place')),
                ('who_gets_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_gets_money_transfer', to='backend_api.user')),
                ('who_paid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_paid_money_transfer', to='backend_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cost', models.FloatField()),
                ('date', models.DateField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.place')),
                ('who_paid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_paid_expense', to='backend_api.user')),
            ],
        ),
    ]
