# Generated by Django 4.2.7 on 2023-12-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='telegram_user_id',
            new_name='telegram_user',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id_telegram_app',
            field=models.IntegerField(unique=True),
        ),
    ]
